/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.15
 * Generated at: 2017-12-26 01:49:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Adding_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1513764755352L));
    _jspx_dependants.put("jar:file:/H:/projectnew/.metadata/.plugins/org.eclipse.wst.server.core/tmp8/wtpwebapps/WearStyleFrontend/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153410282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("body\n");
      out.write("{\n");
      out.write("    background: url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/backgroundnew.jpg') fixed;\n");
      out.write("    background-size: cover;\n");
      out.write("    padding: 0;\n");
      out.write("    margin: 0;\n");
      out.write("   \n");
      out.write("} \n");
      out.write("\n");
      out.write("\n");
      out.write("</style>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\n");
      out.write("<body>\n");
      out.write("<div class=\"container\">\n");
      out.write("<ul class=\"nav nav-tabs\">\n");
      out.write("  <li class=\"active\"><a data-toggle=\"tab\" href=\"#category\">Category</a></li>\n");
      out.write("  <li><a data-toggle=\"tab\" href=\"#supplier\">Supplier</a></li>\n");
      out.write("  <li><a data-toggle=\"tab\" href=\"#product\">Product</a></li>\n");
      out.write("  <li><a data-toggle=\"tab\" href=\"#update\">Update</a></li>\n");
      out.write("</ul>\n");
      out.write("\n");
      out.write("<div class=\"tab-content\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  <div id=\"category\" class=\"tab-pane fade in active\">\n");
      out.write("    <form method=\"post\" action=\"AddCategory\" >\n");
      out.write("    <h3 class=\"input-title\"><font color=\"white\">Category Name</font></h3>\n");
      out.write("    <input class=\"form-control\" type=\"text\" name=\"catgName\" required/>\n");
      out.write("    <h3 class=\"input-title\"><font color=\"white\">Category Description</font></h3>\n");
      out.write("    <input class=\"form-control\" type=\"text\" name=\"catgDescrip\" required/>\n");
      out.write("    <br>\n");
      out.write("    <br>\n");
      out.write("    <center>\n");
      out.write("    <button class=\"btn btn-lg btn-primary\" type=\"submit\">Save</button>\n");
      out.write("    <button class=\"btn btn-lg btn-primary\" type=\"reset\">Cancel</button>\n");
      out.write("    </center>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  \n");
      out.write("  \n");
      out.write("  <div id=\"supplier\" class=\"tab-pane fade\">\n");
      out.write("  <form method=\"post\" action=\"AddSupplier\">\n");
      out.write("  <h3 class=\"input-title\"><font color=\"white\">Supplier Name</font></h3>\n");
      out.write("  <input class=\"form-control\" type=\"text\" name=\"splrName\" required/>\n");
      out.write("  <h3 class=\"input-title\"><font color=\"white\">Supplier Address</font></h3>\n");
      out.write("  <input class=\"form-control\" type=\"text\" name=\"splrAdd\" required/>\n");
      out.write("  <br><br>\n");
      out.write("  <center>\n");
      out.write("    <button class=\"btn btn-lg btn-primary\" type=\"submit\">Save</button>\n");
      out.write("    <button class=\"btn btn-lg btn-primary\" type=\"reset\">Cancel</button>\n");
      out.write("    </center>\n");
      out.write("  </form>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  \n");
      out.write("  \n");
      out.write("  \n");
      out.write("  <div id=\"product\" class=\"tab-pane fade\">\n");
      out.write("  <form method=\"post\" action=\"InsertProduct\" enctype=\"multipart/form-data\" >\n");
      out.write("  <h3 class=\"input-title\"><font color=\"white\">Product Name</font></h3>\n");
      out.write("  <input class=\"form-control\" type=\"text\" name=\"productName\" required/>\n");
      out.write("  <h3 class=\"input-title\"><font color=\"white\">Product Description</font></h3>\n");
      out.write("  <input class=\"form-control\" type=\"text\" name=\"productDesc\" required/>\n");
      out.write("  <h3 class=\"input-title\"><font color=\"white\">Product Stock</font></h3>\n");
      out.write("  <input class=\"form-control\" type=\"number\" name=\"stock\" required/>\n");
      out.write("  <h3 class=\"input-title\"><font color=\"white\">Product Price</font></h3>\n");
      out.write("  <input class=\"form-control\" type=\"number\" name=\"price\" required/>\n");
      out.write("    \n");
      out.write("<div class=\"form-group\">\n");
      out.write("    <h4><font color=\"white\">Select Category</font></h4><br>\n");
      out.write("    <select class=\"form-control\" name=\"cat\" required>\n");
      out.write("    <option value=\"\">------SELECT----------</option>\n");
      out.write("    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    </select>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"form-group\">\n");
      out.write("    <h4><font color=\"white\">Select Supplier</font></h4><br>\n");
      out.write("    <select class=\"form-control\" name=\"sup\" required>\n");
      out.write("    <option value=\"\">------SELECT-----------</option>\n");
      out.write("    ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    </select>\n");
      out.write("</div>\n");
      out.write("<br><br>\n");
      out.write("\n");
      out.write("<div class=\"fileinput fileinput-new\" data provides=\"fileinput\">\n");
      out.write("    <tr>\n");
      out.write("    <td><font color=\"white\">Image File</font></td>\n");
      out.write("    <td><input class=\"form-control\" type=\"file\" name=\"pimage\" accept=\"image/*\"></td>\n");
      out.write("    </tr>\n");
      out.write("</div>\n");
      out.write("<br>\n");
      out.write("<br>\n");
      out.write("\n");
      out.write("   <center>\n");
      out.write("    <button class=\"btn btn-lg btn-primary\" type=\"submit\">Save</button>\n");
      out.write("    <button class=\"btn btn-lg btn-primary\" type=\"reset\">Cancel</button>\n");
      out.write("    </center>\n");
      out.write("</form>\n");
      out.write("  </div>\n");
      out.write("   <div id=\"update\" class=\"tab-pane fade\">\n");
      out.write("     <a href=\"category?status=\"><font color=\"black\"><h4>Category List</h4></font></a><br/>\n");
      out.write("     <a href=\"supplier?status=\"><font color=\"black\"><h4>Supplier List</h4></font></a><br/>\n");
      out.write("     <a href=\"product?status=\"><font color=\"black\"><h4>Product List</h4></font></a><br/>\n");
      out.write("   \n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<br><br><br>\n");
      out.write("<br><br><br><br>\n");
      out.write("<br>\n");
      out.write("<br><br><br>\n");
      out.write("<br><br><br><br><br><br>\n");
      out.write("<br><br>\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/Adding.jsp(85,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/Adding.jsp(85,4) '${categoryList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${categoryList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/Adding.jsp(85,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("category");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("    <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.catgId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.catgName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\n");
            out.write("    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/Adding.jsp(95,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/Adding.jsp(95,4) '${supplierList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${supplierList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/Adding.jsp(95,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("supplier");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("    <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${supplier.splrId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${supplier.splrName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
