/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.15
 * Generated at: 2017-12-26 01:54:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Checkout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1513764755352L));
    _jspx_dependants.put("jar:file:/H:/projectnew/.metadata/.plugins/org.eclipse.wst.server.core/tmp8/wtpwebapps/WearStyleFrontend/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153410282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("     \n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\n");
      out.write("<body>\n");
      out.write("<form action=\"invoiceProcess\" method=\"post\">\n");
      out.write(" <div class='container'>\n");
      out.write("    <div class='row' style='padding-top:25px; padding-bottom:25px;'>\n");
      out.write("        <div class='col-md-12'>\n");
      out.write("            <div id='mainContentWrapper'>\n");
      out.write("                <div class=\"col-md-8 col-md-offset-2\">\n");
      out.write("                    <h2 style=\"text-align: center;\">\n");
      out.write("                        Review Your Order & Complete Checkout\n");
      out.write("                    </h2>\n");
      out.write("                    <hr/>\n");
      out.write("                    <hr/>\n");
      out.write("                   ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\t\t\t ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                    <div class=\"shopping_cart\">\n");
      out.write("                        <form class=\"form-horizontal\" role=\"form\" action=\"\" method=\"post\" id=\"payment-form\">\n");
      out.write("                            <div class=\"panel-group\" id=\"accordion\">\n");
      out.write("                                <div class=\"panel panel-default\">\n");
      out.write("                                    <div class=\"panel-heading\">\n");
      out.write("                                        <h4 class=\"panel-title\">\n");
      out.write("                                            <a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseOne\">Review\n");
      out.write("                                                Your Order</a>\n");
      out.write("                                        </h4>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div id=\"collapseOne\" class=\"panel-collapse collapse in\">\n");
      out.write("                                        <div class=\"panel-body\">\n");
      out.write("                                            <div class=\"items\">\n");
      out.write("                                                <div class=\"col-md-9\">\n");
      out.write("                                                    <table class=\"table table-hover\">\n");
      out.write("                                                        <thead>\n");
      out.write("                    <tr>\n");
      out.write("                        <th>Product</th>\n");
      out.write("                        <th>Quantity</th>\n");
      out.write("                        <th class=\"text-center\">Price</th>\n");
      out.write("                        <th class=\"text-center\">Total</th>\n");
      out.write("                    </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody>\n");
      out.write("                \n");
      out.write("                ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                   \n");
      out.write("                    <tr>\n");
      out.write("                       \n");
      out.write("                        <tr>\n");
      out.write("                        \n");
      out.write("                    </tr>\n");
      out.write("                    \n");
      out.write("                </tbody>\n");
      out.write("                                                    </table>\n");
      out.write("                                                </div>\n");
      out.write("                                                \n");
      out.write("                                                <div class=\"col-md-3\">\n");
      out.write("                                                    <div style=\"text-align: center;\">\n");
      out.write("                                                        <h3>Order Total</h3>\n");
      out.write("                                                        <h3><span style=\"color:green;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gtot}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></h3>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                              \n");
      out.write("                                                \n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                    \n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"panel panel-default\">\n");
      out.write("                                <div class=\"panel-heading\">\n");
      out.write("                                    <h4 class=\"panel-title\">\n");
      out.write("                                        <div style=\"text-align: center; width:100%;\"><a style=\"width:100%;\"\n");
      out.write("                                                                                        data-toggle=\"collapse\"\n");
      out.write("                                                                                        data-parent=\"#accordion\"\n");
      out.write("                                                                                        href=\"#collapseTwo\"\n");
      out.write("                                                                                        class=\" btn btn-success\"\n");
      out.write("                                                                                        onclick=\"$(this).fadeOut(); $('#payInfo').fadeIn();\">Continue\n");
      out.write("                                            to Billing Information»</a></div>\n");
      out.write("                                    </h4>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"panel panel-default\">\n");
      out.write("                                <div class=\"panel-heading\">\n");
      out.write("                                    <h4 class=\"panel-title\">\n");
      out.write("                                        <a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseTwo\">Contact\n");
      out.write("                                            and Billing Information</a>\n");
      out.write("                                    </h4>\n");
      out.write("                                </div>\n");
      out.write("                                <div id=\"collapseTwo\" class=\"panel-collapse collapse\">\n");
      out.write("                                    <div class=\"panel-body\">\n");
      out.write("                                        <b>Help us keep your account safe and secure, please verify your billing\n");
      out.write("                                            information.</b>\n");
      out.write("                                        <br/><br/>\n");
      out.write("                                        <table class=\"table table-striped\" style=\"font-weight: bold;\">\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td style=\"width: 175px;\">\n");
      out.write("                                                    <label for=\"id_email\">Email:</label></td>\n");
      out.write("                                                <td>\n");
      out.write("                                                    <input class=\"form-control\" id=\"id_email\" name=\"email\"\n");
      out.write("                                                           required=\"required\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${User.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("                                                </td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td style=\"width: 175px;\">\n");
      out.write("                                                    <label for=\"id_name\">Name:</label></td>\n");
      out.write("                                                <td>\n");
      out.write("                                                    <input class=\"form-control\" id=\"id_first_name\" name=\"name\"\n");
      out.write("                                                           required=\"required\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${User.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("                                                </td>\n");
      out.write("                                            </tr>\n");
      out.write("                                           \n");
      out.write("                                            <tr>\n");
      out.write("                                                <td style=\"width: 175px;\">\n");
      out.write("                                                    <label for=\"id_address_line_1\">Address:</label></td>\n");
      out.write("                                                <td>\n");
      out.write("                                                    <input class=\"form-control\" id=\"id_address_line_1\"\n");
      out.write("                                                           name=\"address\" required=\"required\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${User.address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("                                                </td>\n");
      out.write("                                            </tr>\n");
      out.write("                                           \n");
      out.write("                                            <tr>\n");
      out.write("                                                <td style=\"width: 175px;\">\n");
      out.write("                                                    <label for=\"id_city\">City:</label></td>\n");
      out.write("                                                <td>\n");
      out.write("                                                    <input class=\"form-control\" id=\"id_city\" name=\"city\"\n");
      out.write("                                                           required=\"required\" type=\"text\"/>\n");
      out.write("                                                </td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td style=\"width: 175px;\">\n");
      out.write("                                                    <label for=\"id_state\">State:</label></td>\n");
      out.write("                                                <td>\n");
      out.write("                                           <input class=\"form-control\" id=\"id_state\" name=\"state\"\n");
      out.write("                                                           required=\"required\" type=\"text\"/>\n");
      out.write("                                                </td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td style=\"width: 175px;\">\n");
      out.write("                                                    <label for=\"id_postalcode\">Postalcode:</label></td>\n");
      out.write("                                                <td>\n");
      out.write("                                                    <input class=\"form-control\" id=\"id_postalcode\" name=\"postalcode\"\n");
      out.write("                                                           required=\"required\" type=\"text\"/>\n");
      out.write("                                                </td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td style=\"width: 175px;\">\n");
      out.write("                                                    <label for=\"id_phone\">Phone:</label></td>\n");
      out.write("                                                <td>\n");
      out.write("                                                    <input class=\"form-control\" id=\"id_phone\" name=\"phone\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${User.phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("                                                </td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td style=\"width: 175px;\">\n");
      out.write("                                                    <label for=\"id_country\">Country:</label></td>\n");
      out.write("                                                <td>\n");
      out.write("                                                    <input class=\"form-control\" id=\"id_country\" name=\"country\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${User.country}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("                                                </td>\n");
      out.write("                                            </tr>\n");
      out.write("\n");
      out.write("                                        </table>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"panel panel-default\">\n");
      out.write("                                <div class=\"panel-heading\">\n");
      out.write("                                    <h4 class=\"panel-title\">\n");
      out.write("                                        <div style=\"text-align: center;\"><a data-toggle=\"collapse\"\n");
      out.write("                                                                            data-parent=\"#accordion\"\n");
      out.write("                                                                            href=\"#collapseThree\"\n");
      out.write("                                                                            class=\" btn   btn-success\" id=\"payInfo\"\n");
      out.write("                                                                            style=\"width:100%;display: none;\" onclick=\"$(this).fadeOut();  \n");
      out.write("                   document.getElementById('collapseThree').scrollIntoView()\">Enter Payment Information »</a>\n");
      out.write("                                        </div>\n");
      out.write("                                    </h4>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"panel panel-default\">\n");
      out.write("                                <div class=\"panel-heading\">\n");
      out.write("                                    <h4 class=\"panel-title\">\n");
      out.write("                                        <a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseThree\">\n");
      out.write("                                            <b>Payment Information</b>\n");
      out.write("                                        </a>\n");
      out.write("                                    </h4>\n");
      out.write("                                </div>\n");
      out.write("                                <div id=\"collapseThree\" class=\"panel-collapse collapse\">\n");
      out.write("                                    <div class=\"panel-body\">\n");
      out.write("                                        <span class='payment-errors'></span>\n");
      out.write("                                        <fieldset>\n");
      out.write("                                          \n");
      out.write("                                            <div class=\"form-group\">\n");
      out.write("                                                <label class=\"col-sm-3 control-label\" for=\"card-holder-name\">Name on\n");
      out.write("                                                    Card</label>\n");
      out.write("                                                <div class=\"col-sm-9\">\n");
      out.write("                                                    <input type=\"text\" class=\"form-control\" stripe-data=\"name\"\n");
      out.write("                                                           id=\"name-on-card\" placeholder=\"Card Holder's Name\">\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"form-group\">\n");
      out.write("                                                <label class=\"col-sm-3 control-label\" for=\"card-number\">Card\n");
      out.write("                                                    Number</label>\n");
      out.write("                                                <div class=\"col-sm-9\">\n");
      out.write("                                                    <input type=\"text\" class=\"form-control\" stripe-data=\"number\"\n");
      out.write("                                                           id=\"card-number\" placeholder=\"Debit/Credit Card Number\">\n");
      out.write("                                                    <br/>\n");
      out.write("                                                    <div><img class=\"pull-right\"\n");
      out.write("                                                              src=\"https://s3.amazonaws.com/hiresnetwork/imgs/cc.png\"\n");
      out.write("                                                              style=\"max-width: 250px; padding-bottom: 20px;\">\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"form-group\">\n");
      out.write("                                                    <label class=\"col-sm-3 control-label\" for=\"expiry-month\">Expiration\n");
      out.write("                                                        Date</label>\n");
      out.write("                                                    <div class=\"col-sm-9\">\n");
      out.write("                                                        <div class=\"row\">\n");
      out.write("                                                            <div class=\"col-xs-3\">\n");
      out.write("                                                                <select class=\"form-control col-sm-2\"\n");
      out.write("                                                                        data-stripe=\"exp-month\" id=\"card-exp-month\"\n");
      out.write("                                                                        style=\"margin-left:5px;\">\n");
      out.write("                                                                    <option>Month</option>\n");
      out.write("                                                                    <option value=\"01\">Jan (01)</option>\n");
      out.write("                                                                    <option value=\"02\">Feb (02)</option>\n");
      out.write("                                                                    <option value=\"03\">Mar (03)</option>\n");
      out.write("                                                                    <option value=\"04\">Apr (04)</option>\n");
      out.write("                                                                    <option value=\"05\">May (05)</option>\n");
      out.write("                                                                    <option value=\"06\">June (06)</option>\n");
      out.write("                                                                    <option value=\"07\">July (07)</option>\n");
      out.write("                                                                    <option value=\"08\">Aug (08)</option>\n");
      out.write("                                                                    <option value=\"09\">Sep (09)</option>\n");
      out.write("                                                                    <option value=\"10\">Oct (10)</option>\n");
      out.write("                                                                    <option value=\"11\">Nov (11)</option>\n");
      out.write("                                                                    <option value=\"12\">Dec (12)</option>\n");
      out.write("                                                                </select>\n");
      out.write("                                                            </div>\n");
      out.write("                                                            <div class=\"col-xs-3\">\n");
      out.write("                                                                <select class=\"form-control\" data-stripe=\"exp-year\"\n");
      out.write("                                                                        id=\"card-exp-year\">\n");
      out.write("                                                                    <option value=\"2016\">2016</option>\n");
      out.write("                                                                    <option value=\"2017\">2017</option>\n");
      out.write("                                                                    <option value=\"2018\">2018</option>\n");
      out.write("                                                                    <option value=\"2019\">2019</option>\n");
      out.write("                                                                    <option value=\"2020\">2020</option>\n");
      out.write("                                                                    <option value=\"2021\">2021</option>\n");
      out.write("                                                                    <option value=\"2022\">2022</option>\n");
      out.write("                                                                    <option value=\"2023\">2023</option>\n");
      out.write("                                                                    <option value=\"2024\">2024</option>\n");
      out.write("                                                                </select>\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"form-group\">\n");
      out.write("                                                    <label class=\"col-sm-3 control-label\" for=\"cvv\">Card CVC</label>\n");
      out.write("                                                    <div class=\"col-sm-3\">\n");
      out.write("                                                        <input type=\"text\" class=\"form-control\" stripe-data=\"cvc\"\n");
      out.write("                                                               id=\"card-cvc\" placeholder=\"Security Code\">\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"form-group\">\n");
      out.write("                                                    <div class=\"col-sm-offset-3 col-sm-9\">\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                        </fieldset>\n");
      out.write("                                        <input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gtot}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"total\"/>\n");
      out.write("                                        <button type=\"submit\" class=\"btn btn-success btn-lg\" style=\"width:100%;\">Invoice\n");
      out.write("                                        </button>\n");
      out.write("                                        <br/>\n");
      out.write("                                       \n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("  \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/Checkout.jsp(23,19) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("gtot");
      // /WEB-INF/views/Checkout.jsp(23,19) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/Checkout.jsp(23,19) '0'",_jsp_getExpressionFactory().createValueExpression("0",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/Checkout.jsp(24,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("c");
      // /WEB-INF/views/Checkout.jsp(24,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/Checkout.jsp(24,8) '${Cart}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${Cart}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("\t\t\t\t\t\t     ");
            if (_jspx_meth_c_005fset_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/Checkout.jsp(25,11) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("gtot");
      // /WEB-INF/views/Checkout.jsp(25,11) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/Checkout.jsp(25,11) '${gtot+c.product.price*c.cartQnty}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${gtot+c.product.price*c.cartQnty}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/Checkout.jsp(52,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("c");
      // /WEB-INF/views/Checkout.jsp(52,16) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/Checkout.jsp(52,16) '${Cart}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${Cart}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                    <tr>\n");
            out.write("                        <td class=\"col-sm-8 col-md-6\">\n");
            out.write("                        <div class=\"media\">\n");
            out.write("                            <a class=\"thumbnail pull-left\" href=\"#\"><img class=\"media-object\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.product.productId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(".jpg\" style=\"width: 72px; height: 72px;\"> </a>\n");
            out.write("                            <div class=\"media-body\">\n");
            out.write("                                <h4 class=\"media-heading\"><a href=\"#\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.product.productName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></h4>\n");
            out.write("                                <h5 class=\"media-heading\"> by <a href=\"#\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.product.supplier.splrName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></h5>\n");
            out.write("                               \n");
            out.write("                            </div>\n");
            out.write("                        </div></td>\n");
            out.write("                     \n");
            out.write("                        <td class=\"col-sm-1 col-md-1\" style=\"text-align: center\">\n");
            out.write("                         ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.cartQnty}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\n");
            out.write("                        </td>\n");
            out.write("                        <td class=\"col-sm-1 col-md-1 text-center\"><strong>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.product.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</strong></td>\n");
            out.write("                        <td class=\"col-sm-1 col-md-1 text-center\"><strong>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.cartQnty*c.product.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</strong></td>\n");
            out.write("                        <td class=\"col-sm-1 col-md-1\">\n");
            out.write("                        \n");
            out.write("       \t\t\t\t    </td>\n");
            out.write("\t\t\t\t\t\n");
            out.write("                        </tr>\n");
            out.write("                    <tr>\n");
            out.write("                        \n");
            out.write("                        \n");
            out.write("                       \n");
            out.write("                    </tr>\n");
            out.write("                    \n");
            out.write("                   \n");
            out.write("                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
