/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.15
 * Generated at: 2017-12-22 08:42:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ProductDescp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1513764755352L));
    _jspx_dependants.put("jar:file:/H:/projectnew/.metadata/.plugins/org.eclipse.wst.server.core/tmp8/wtpwebapps/WearStyleFrontend/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153410282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("    \n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\n");
      out.write("/*****************globals*************/\n");
      out.write("\n");
      out.write("body\n");
      out.write("{\n");
      out.write("  background-image: url(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/wallpaper.wiki-Background-HD-Images-Screen-Download-PIC-WPD0013520.jpg\");\n");
      out.write("  background-size: cover;\n");
      out.write("  padding=0;\n");
      out.write("  margin=0;\n");
      out.write(" \n");
      out.write("}\n");
      out.write("img {\n");
      out.write("  max-width: 100%; }\n");
      out.write("\n");
      out.write(".preview {\n");
      out.write("  display: -webkit-box;\n");
      out.write("  display: -webkit-flex;\n");
      out.write("  display: -ms-flexbox;\n");
      out.write("  display: flex;\n");
      out.write("  -webkit-box-orient: vertical;\n");
      out.write("  -webkit-box-direction: normal;\n");
      out.write("  -webkit-flex-direction: column;\n");
      out.write("      -ms-flex-direction: column;\n");
      out.write("          flex-direction: column; }\n");
      out.write("  @media screen and (max-width: 996px) {\n");
      out.write("    .preview {\n");
      out.write("      margin-bottom: 20px; } }\n");
      out.write("\n");
      out.write(".preview-pic {\n");
      out.write("  -webkit-box-flex: 1;\n");
      out.write("  -webkit-flex-grow: 1;\n");
      out.write("      -ms-flex-positive: 1;\n");
      out.write("          flex-grow: 1; }\n");
      out.write("\n");
      out.write(".preview-thumbnail.nav-tabs {\n");
      out.write("  border: none;\n");
      out.write("  margin-top: 15px; }\n");
      out.write("  .preview-thumbnail.nav-tabs li {\n");
      out.write("    width: 18%;\n");
      out.write("    margin-right: 2.5%; }\n");
      out.write("    .preview-thumbnail.nav-tabs li img {\n");
      out.write("      max-width: 100%;\n");
      out.write("      display: block; }\n");
      out.write("    .preview-thumbnail.nav-tabs li a {\n");
      out.write("      padding: 0;\n");
      out.write("      margin: 0; }\n");
      out.write("    .preview-thumbnail.nav-tabs li:last-of-type {\n");
      out.write("      margin-right: 0; }\n");
      out.write("\n");
      out.write(".tab-content {\n");
      out.write("  overflow: hidden; }\n");
      out.write("  .tab-content img {\n");
      out.write("    width: 100%;\n");
      out.write("    -webkit-animation-name: opacity;\n");
      out.write("            animation-name: opacity;\n");
      out.write("    -webkit-animation-duration: .3s;\n");
      out.write("            animation-duration: .3s; }\n");
      out.write("\n");
      out.write(".card {\n");
      out.write("  margin-top: 50px;\n");
      out.write("  background: #eee;\n");
      out.write("  padding: 3em;\n");
      out.write("  line-height: 1.5em; }\n");
      out.write("\n");
      out.write("@media screen and (min-width: 997px) {\n");
      out.write("  .wrapper {\n");
      out.write("    display: -webkit-box;\n");
      out.write("    display: -webkit-flex;\n");
      out.write("    display: -ms-flexbox;\n");
      out.write("    display: flex; } }\n");
      out.write("\n");
      out.write(".details {\n");
      out.write("  display: -webkit-box;\n");
      out.write("  display: -webkit-flex;\n");
      out.write("  display: -ms-flexbox;\n");
      out.write("  display: flex;\n");
      out.write("  -webkit-box-orient: vertical;\n");
      out.write("  -webkit-box-direction: normal;\n");
      out.write("  -webkit-flex-direction: column;\n");
      out.write("      -ms-flex-direction: column;\n");
      out.write("          flex-direction: column; }\n");
      out.write("\n");
      out.write(".colors {\n");
      out.write("  -webkit-box-flex: 1;\n");
      out.write("  -webkit-flex-grow: 1;\n");
      out.write("      -ms-flex-positive: 1;\n");
      out.write("          flex-grow: 1; }\n");
      out.write("\n");
      out.write(".product-title, .price, .sizes, .colors {\n");
      out.write("  text-transform: UPPERCASE;\n");
      out.write("  font-weight: bold; }\n");
      out.write("\n");
      out.write(".checked, .price span {\n");
      out.write("  color: #ff9f1a; }\n");
      out.write("\n");
      out.write(".product-title, .rating, .product-description, .price, .vote, .sizes {\n");
      out.write("  margin-bottom: 15px; }\n");
      out.write("\n");
      out.write(".product-title {\n");
      out.write("  margin-top: 0; }\n");
      out.write("\n");
      out.write(".size {\n");
      out.write("  margin-right: 10px; }\n");
      out.write("  .size:first-of-type {\n");
      out.write("    margin-left: 40px; }\n");
      out.write("\n");
      out.write(".color {\n");
      out.write("  display: inline-block;\n");
      out.write("  vertical-align: middle;\n");
      out.write("  margin-right: 10px;\n");
      out.write("  height: 2em;\n");
      out.write("  width: 2em;\n");
      out.write("  border-radius: 2px; }\n");
      out.write("  .color:first-of-type {\n");
      out.write("    margin-left: 20px; }\n");
      out.write("\n");
      out.write(".add-to-cart, .like {\n");
      out.write("  background: #ff9f1a;\n");
      out.write("  padding: 1.2em 1.5em;\n");
      out.write("  border: none;\n");
      out.write("  text-transform: UPPERCASE;\n");
      out.write("  font-weight: bold;\n");
      out.write("  color: #fff;\n");
      out.write("  -webkit-transition: background .3s ease;\n");
      out.write("          transition: background .3s ease; }\n");
      out.write("  .add-to-cart:hover, .like:hover {\n");
      out.write("    background: #b36800;\n");
      out.write("    color: #fff; }\n");
      out.write("\n");
      out.write(".not-available {\n");
      out.write("  text-align: center;\n");
      out.write("  line-height: 2em; }\n");
      out.write("  .not-available:before {\n");
      out.write("    font-family: fontawesome;\n");
      out.write("    content: \"\\f00d\";\n");
      out.write("    color: #fff; }\n");
      out.write("\n");
      out.write(".orange {\n");
      out.write("  background: #ff9f1a; }\n");
      out.write("\n");
      out.write(".green {\n");
      out.write("  background: #85ad00; }\n");
      out.write("\n");
      out.write(".blue {\n");
      out.write("  background: #0076ad; }\n");
      out.write("\n");
      out.write(".tooltip-inner {\n");
      out.write("  padding: 1.3em; }\n");
      out.write("\n");
      out.write("@-webkit-keyframes opacity {\n");
      out.write("  0% {\n");
      out.write("    opacity: 0;\n");
      out.write("    -webkit-transform: scale(3);\n");
      out.write("            transform: scale(3); }\n");
      out.write("  100% {\n");
      out.write("    opacity: 1;\n");
      out.write("    -webkit-transform: scale(1);\n");
      out.write("            transform: scale(1); } }\n");
      out.write("\n");
      out.write("@keyframes opacity {\n");
      out.write("  0% {\n");
      out.write("    opacity: 0;\n");
      out.write("    -webkit-transform: scale(3);\n");
      out.write("            transform: scale(3); }\n");
      out.write("  100% {\n");
      out.write("    opacity: 1;\n");
      out.write("    -webkit-transform: scale(1);\n");
      out.write("            transform: scale(1); } }\n");
      out.write("\n");
      out.write("/*# sourceMappingURL=style.css.map */\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("\t\t<div class=\"card\">\n");
      out.write("\t\t\t<div class=\"container-fliud\">\n");
      out.write("\t\t\t\t<div class=\"wrapper row\">\n");
      out.write("\t\t\t\t\t<div class=\"preview col-md-6\">\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<div class=\"preview-pic tab-content\">\n");
      out.write("\t\t\t\t\t\t  <div class=\"tab-pane active\" id=\"pic-1\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.productId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".jpg\" /></div>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"details col-md-6\">\n");
      out.write("\t\t\t\t\t\t<h3 class=\"product-title\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.productName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\n");
      out.write("\t\t\t\t\t\t<div class=\"rating\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"stars\">\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"fa fa-star checked\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"fa fa-star checked\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"fa fa-star checked\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"fa fa-star\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"fa fa-star\"></span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<p class=\"product-description\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.productDesc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("\t\t\t\t\t\t<h4 class=\"price\">current price: <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></h4>\n");
      out.write("\t\t\t\t\t\t<h5 class=\"price\">Available Stock : <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.stock}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></h4>\n");
      out.write("\t\t\t\t\t\t<form action=\"addCart\" method=\"post\">\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t <div>\n");
      out.write("                           <input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.productId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"pid\">\n");
      out.write("                          Quantity : <input value=\"1\"  type=\"number\" min=\"1\" name=\"qty\"/>\n");
      out.write("                          <h1 style=\"color: red;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\n");
      out.write("                  \n");
      out.write("                        </div>\n");
      out.write("                        <br/>\n");
      out.write("                        \n");
      out.write("                  <button class=\"btn btn-success\" type=\"submit\"><span style=\"margin-right:20px\" class=\"glyphicon glyphicon-shopping-cart\" aria-hidden=\"true\"></span> ADD TO CART</button>\n");
      out.write("              \n");
      out.write("          \n");
      out.write("             \n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<!--  <div class=\"section\" style=\"padding-bottom:20px;\">\n");
      out.write("\t\t\t\t\t\t \n");
      out.write("                        <button type=\"submit\"class=\"btn btn-success\"><span style=\"margin-right:20px\" class=\"glyphicon glyphicon-shopping-cart\" aria-hidden=\"true\"></span> Add to Cart</button> -->\n");
      out.write("                       </form>\n");
      out.write("                     \n");
      out.write("                    </div>  \n");
      out.write("\t\t\t\t\t</div> \t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
